version: "3.7"

services:
  wildbutton-production:
    image: ghcr.io/zozs/wildbutton:latest
    environment:
      PORT: 9850
    env_file:
      - .env.production
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wildbutton-production.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.wildbutton-production.entrypoints=websecure"
      - "traefik.http.routers.wildbutton-production.tls.certresolver=myresolver"
      - "traefik.http.services.wildbutton-production.loadbalancer.server.port=9850"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
