name: Vulnerability scan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  vulnerabilities-scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: debricked/actions@v3
      env:
        DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN }}
